version: "3.3"

services:
  db:
    image: postgres:13.0
    container_name: seabot-db
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seabot